#!/bin/bash

prog="
Catfish
Geany
Thunar
Terminal
Firefox
Thunderbird
Pragha
Smplayer
Writer
Gimp
Gpicview
Synaptic
Screenshot
Suspend
ScreenLock
Exit"

cmd=$(dmenu -nb '#0F171A' -nf '#93ADAC' -sb '#007187' -sf '#E0FCFF' -fn 'Liberation Sans-11' <<< "$prog")

case ${cmd%% *} in

	Catfish)		exec catfish ;;
	Geany)			exec geany ;;
	Thunar)		        exec thunar ;;
	Terminal)		exec x-terminal-emulator ;;
	Firefox)		exec firefox ;;
	Thunderbird)		exec thunderbird ;;
	Pragha) 		exec pragha ;;
	Smplayer)		exec smplayer ;;
	Writer)			exec libreoffice ;;
	Gimp)			exec gimp ;;
	Gpicview)		exec gpicview ;;
	Synaptic)		exec gksudo synaptic ;;
	Screenshot)		exec gnome-screenshot -i ;;
	Suspend)		exec systemctl suspend ;;
	ScreenLock)		exec slock ;;
	Exit)			exec ld-logout ;;
esac
