#!/bin/bash
#### A theme changer to set the theme to your own custom configuration.
### Simply change the "Lilidog" entries below with your own selections.
## Change any of the themes however you like to create custom entries.
# You can also add anything that can be refreshed, wallpaper, conky, etc . . .

# Change gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Conanolis"


## Change openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Conanolisbox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Conanolisbox" ~/.config/openbox/rc.xml
openbox --reconfigure


## Change Geany theme
sed -i "s/color_scheme=.*/color_scheme=Conanolis.conf/g" ~/.config/geany/geany.conf


# Change jgmenu theme
#jgmenu_run gtktheme
jgmenu_run init --apply-obtheme

## Change xfce4-terminal theme
xfce4-term-colors cananolis

# COMMENT THE LINE BELOW FOR THE LIGHT THEME USED IN THE LIGHT/DARK TOGGLE
rm ~/.cache/temp_theme
