#!/bin/bash
#### A theme changer to set the theme to your own custom configuration.
### Simply change the "Lilidog" entries below with your own selections.
## Change any of the themes however you like to create custom entries.
# You can also add anything that can be refreshed, wallpaper, conky, etc . . .

## Lightdm Greeter settings for theme, wallpaper, position, icons, and font. (Requires Sudo)
sudo sed -i "s/theme-name.*/theme-name = Arcadia/g" /etc/lightdm/lightdm-gtk-greeter.conf
sudo sed -i "s/background.*/background = \/\home\/\wallpaper\/Arcadia.png/g" /etc/lightdm/lightdm-gtk-greeter.conf
sudo sed -i "s/position.*/position = -4%,end 4%,start/g" /etc/lightdm/lightdm-gtk-greeter.conf
sudo sed -i "s/font-name.*/font-name = Noto Sans 11/g" /etc/lightdm/lightdm-gtk-greeter.conf

# System gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Arcadia"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Blue"

## System Fonts
xfconf-query -c xsettings -p /Gtk/FontName -s "Noto Sans 11"
xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "Monospace 10"

## Openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Arcadiabox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Arcadiabox" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:font/o:size' -v "12" ~/.config/openbox/rc.xml
openbox --reconfigure


## Geany theme
sed -i "s/color_scheme=.*/color_scheme=Arcadia.conf/g" ~/.config/geany/geany.conf
sed -i "s/editor_font=.*/editor_font=JetBrains Mono 11/g" ~/.config/geany/geany.conf

## jgmenu theme
jgmenu_run init --apply-obtheme
#jgmenu_run gtktheme

## jgmenu font
sed -i "s/font =.*/font = Noto Sans 11/g" ~/.config/jgmenu/jgmenurc

## jgmenu Icon Theme
sed -i 's/^icon_size.*/icon_size = 20/g' ~/.config/jgmenu/jgmenurc
sed -i 's/^icon_theme =.*/icon_theme = gnome/g' ~/.config/jgmenu/jgmenurc

## xfce4-terminal theme
xfce4-term-colors arcadia
sed -i "s/FontName=.*/FontName=JetBrains Mono 11/g" ~/.config/xfce4/terminal/terminalrc

## Tint2 Panel Items - position, autoshrink, autohide, and transparency
sed -i "s/^panel_position =.*/panel_position = bottom center horizontal/" "$HOME"/.config/tint2/tint2rc
sed -i "s/^panel_shrink =.*/panel_shrink = 0/" "$HOME"/.config/tint2/tint2rc
sed -i "s/^autohide =.*/autohide = 0/" "$HOME"/.config/tint2/tint2rc
sed -i "0,/background_color =/{s/background_color =.*/background_color = #0d0f0f 60/}" "$HOME"/.config/tint2/tint2rc
## Tint2 Icon colors
sed -i 's/coltint2.*\//coltint2base\//g' "$HOME"/.config/tint2/tint2rc
## Tint2 Font colors
sed -i 's/taskbar_name_font_color =.*/taskbar_name_font_color = \#C1CFDB 100/' "$HOME"/.config/tint2/tint2rc
sed -i 's/taskbar_name_active_font_color =.*/taskbar_name_active_font_color = \#C1CFDB 100/' "$HOME"/.config/tint2/tint2rc
sed -i 's/task_font_color =.*/task_font_color = \#C1CFDB 100/' "$HOME"/.config/tint2/tint2rc
sed -i 's/clock_font_color =.*/clock_font_color = \#C1CFDB 100/' "$HOME"/.config/tint2/tint2rc
sed -i 's/tooltip_font_color =.*/tooltip_font_color = \#C1CFDB 100/' "$HOME"/.config/tint2/tint2rc
sed -i 's/^battery_font_color.*/battery_font_color = #C1CFDB 100/g' "$HOME"/.config/tint2/tint2rc
killall -SIGUSR1 tint2

## Feh Background
feh --bg-scale '/home/wallpaper/Arcadia.png'

## Sounds - Dunst
sed -i '/summary/d' ~/.config/dunst/dunstrc
sed -i '/sounds/d' ~/.config/dunst/dunstrc
killall -q dunst

### Conky
## transparency 
    sed -i "s/bg_alpha=.*/bg_alpha=0.0/g" ~/.config/conky/lua/shortcuts.lua
    sed -i "s/bg_alpha=.*/bg_alpha=0.0/g" ~/.config/conky/lua/tao.lua
    sed -i "s/bg_alpha=.*/bg_alpha=0.0/g" ~/.config/conky/lua/full.lua
    sed -i "s/bg_alpha=.*/bg_alpha=0.0/g" ~/.config/conky/lua/fortunes.lua
    sed -i "s/bg_alpha=.*/bg_alpha=0.0/g" ~/.config/conky/lua/current.lua
    sed -i "s/bg_alpha=.*/bg_alpha=0.0/g" ~/.config/conky/lua/clock-date.lua
    sed -i "s/bg_alpha=.*/bg_alpha=0.0/g" ~/.config/conky/lua/world.lua
    sed -i "s/bg_alpha=.*/bg_alpha=0.0/g" ~/.config/conky/lua/build.lua
## color
    sed -i "s/bg_colour=.*/bg_colour=0x000000/g" ~/.config/conky/lua/shortcuts.lua
    sed -i "s/bg_colour=.*/bg_colour=0x000000/g" ~/.config/conky/lua/tao.lua
    sed -i "s/bg_colour=.*/bg_colour=0x000000/g" ~/.config/conky/lua/full.lua
    sed -i "s/bg_colour=.*/bg_colour=0x000000/g" ~/.config/conky/lua/fortunes.lua
    sed -i "s/bg_colour=.*/bg_colour=0x000000/g" ~/.config/conky/lua/current.lua
    sed -i "s/bg_colour=.*/bg_colour=0x000000/g" ~/.config/conky/lua/clock-date.lua
    sed -i "s/bg_colour=.*/bg_colour=0x000000/g" ~/.config/conky/lua/world.lua
    sed -i "s/bg_colour=.*/bg_colour=0x000000/g" ~/.config/conky/lua/build.lua
killall -q conky
if test -f "$HOME"/.config/conky/conky-shortcuts.conf; then
set -m; nohup conky -q -c "$HOME/.config/conky/conky-shortcuts.conf" &> /dev/null
fi
#(setsid conky -q -c "$HOME/.config/conky/conky-shortcuts.conf" &)

# These lines are for the light/dark toggle and the custom toggle. Do not remove.
# Comment these lines in Custom-Theme or Light-Dark-Theme if copying a named theme.
rm -f ~/.cache/temp_theme
rm -f ~/.cache/custom_theme
