#!/bin/bash
#### A theme changer to set the theme to your own custom configuration.
### Simply change the "Lilidog" entries below with your own selections.

## Change gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Orchis-Light"

## Change openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Orchis-Lightbox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Orchis-Lightbox" ~/.config/openbox/rc.xml
openbox --reconfigure

## Change Geany theme
sed -i "s/color_scheme=.*/color_scheme=Adwaita-ld.conf/g" ~/.config/geany/geany.conf

## Change jgmenu theme
# jgmenu_run gtktheme
jgmenu_run init --apply-obtheme

## Change xfce4-terminal theme
xfce4-term-colors adwaita-ld

# These lines are for the light/dark toggle and the custom toggle. Do not remove.
# Comment these lines in Custom-Theme or Light-Dark-Theme if copying a named theme.
rm ~/.cache/temp_theme
rm ~/.cache/custom_theme
