#!/bin/bash

toggle_conky () {
#  toggle individual conky on/off

if pgrep -f ${1}.conf > /dev/null; then
    pkill -f ${1}.conf
else
    conky -c $HOME/.config/conky/${1}.conf
fi
}
export -f toggle_conky

yad --title "Conky" --button=gtk-close:1 --form --center --width=230 \
--height=340 --text="\n TOGGLE YOUR\n SELECTIONS. \n" --text-align=center \
--window-icon=applications-system \
    --form \
    --field="Conky Full":BTN "bash -c 'toggle_conky conky-full'" \
    --field="Conky Min":BTN "bash -c 'toggle_conky conky-min'" \
    --field="Conky Shortcuts":BTN "bash -c 'toggle_conky conky-shortcuts'" \
    --field="Conky Shortcuts-Dark":BTN "bash -c 'toggle_conky conky-shortcuts-dark'" \
    --field="Restart Conky":fbtn "killall -SIGUSR1 conky" \
    --field="Kill Conky":fbtn "killall conky" 
