#!/bin/bash

# Made by sleekmason 1-15-2022

time_format=$(grep -E "%H" ~/.config/conky/conky-shortcuts.conf)

if [[ "$time_format" ]]; then
sed -i 's/%H/%I/g' ~/.config/conky/conky-clock-date.conf
sed -i 's/%H/%I/g' ~/.config/conky/conky-shortcuts.conf
notify-send "Conky Time Format Changed To 12H"
  else
sed -i 's/%I/%H/g' ~/.config/conky/conky-clock-date.conf
sed -i 's/%I/%H/g' ~/.config/conky/conky-shortcuts.conf
notify-send "Conky Time Format Changed To 24H"
fi

exit
