#!/bin/bash

toggle_conky () {
#  toggle individual conky on/off

if pgrep -f ${1}.conf > /dev/null; then
    pkill -f ${1}.conf
else
    conky -c $HOME/.config/conky/${1}.conf
fi
}
export -f toggle_conky

yad --title "Conky" --button=gtk-close:1 --form --center --width=230 \
--height=340 --text="\n PLEASE TOGGLE\n YOUR SELECTIONS. \n" --text-align=center \
--window-icon=applications-system \
    --form \
    --field="Clock":BTN "bash -c 'toggle_conky conky-clock-date'" \
    --field="Shortcuts":BTN "bash -c 'toggle_conky conky-shortcuts'" \
    --field="Full Conky":BTN "bash -c 'toggle_conky conky-full'" \
    --field="Fortunes":BTN "bash -c 'toggle_conky conky-fortunes'" \
    --field="Restart Conky":fbtn "killall -SIGUSR1 conky" \
    --field="Kill Conky":fbtn "killall conky" 
