#!/bin/dash

## Use df -h --output to find the filesystem types for Conky
df -h -t ext4 -t vfat -t msdos -t exfat -t fuseblk -t ntfs -t iso9660 -t udf -t fuse.sshfs --output=source,fstype,pcent | grep -v "boot" 
